// @ts-check
// verdict.proof-packet/v1 conformance: golden vectors generated by verdict-cli
// (canonical copy: verdict-cli/tests/proof_packet_vectors.json, vendored
// byte-identically in src/__fixtures__/proof_packet_vectors.json). These tests
// are the executable proof that a packet produced by the Python CLI verifies
// in this SDK: same JCS canonical bytes, same BLAKE3 content hash, and a
// verifying Ed25519 signature (fixed PUBLIC RFC 8032 §7.1 TEST 1 key).
// NOTE: this is a DIFFERENT contract from verifyWarrantProofPacket
// ("meridian-warrant-proof-packet/0.1").
import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const sdk = await import("../dist/index.mjs");
const {
  jcsStringify,
  blake3Hex,
  verifyProofPacket,
  validateProofPacket,
  PROOF_PACKET_SCHEMA,
} = sdk;

const here = dirname(fileURLToPath(import.meta.url));
const fixture = JSON.parse(
  readFileSync(join(here, "__fixtures__", "proof_packet_vectors.json"), "utf8"),
);

const utf8 = (s) => new TextEncoder().encode(s);
const clone = (v) => JSON.parse(JSON.stringify(v));

describe("verdict.proof-packet/v1 golden vectors (verdict-cli parity)", () => {
  it("fixture declares the packet schema and the RFC 8032 TEST 1 key", () => {
    assert.equal(fixture.schema, PROOF_PACKET_SCHEMA);
    assert.ok(fixture.vectors.length >= 3);
    assert.equal(
      fixture.fixed_test_key.ed25519_pubkey_hex,
      "d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a",
    );
  });

  for (const v of fixture.vectors) {
    it(`${v.name}: packet passes structural validation`, async () => {
      assert.deepEqual(await validateProofPacket(v.packet), { valid: true, errors: [] });
    });

    it(`${v.name}: JCS canonical bytes match the verdict-cli golden`, () => {
      assert.equal(jcsStringify(v.packet), v.expected_jcs);
    });

    it(`${v.name}: JCS→BLAKE3 content hash matches the golden`, async () => {
      assert.equal(await blake3Hex(utf8(jcsStringify(v.packet))), v.expected_content_hash);
    });

    it(`${v.name}: signed envelope verifies end to end`, async () => {
      const res = await verifyProofPacket(v.envelope);
      assert.equal(res.kind, "verdict_v1_envelope");
      assert.equal(res.valid, true);
      assert.equal(res.signature_valid, true);
      assert.deepEqual(res.errors, []);
      assert.equal(res.content_hash, v.expected_content_hash);
      assert.equal(res.signer_pubkey, fixture.fixed_test_key.ed25519_pubkey_hex);
      assert.equal(res.subject, v.packet.subject);
      assert.equal(res.action, v.packet.action);
      assert.equal(res.unit_id, v.packet.unit.id);
    });

    it(`${v.name}: raw packet validates without claiming a signature check`, async () => {
      const res = await verifyProofPacket(clone(v.packet));
      assert.equal(res.kind, "proof_packet");
      assert.equal(res.valid, true);
      assert.equal(res.signature_valid, null);
    });

    it(`${v.name}: tampered receipt fails signature verification`, async () => {
      const tampered = clone(v.envelope);
      tampered.receipt.subject = "tampered";
      const res = await verifyProofPacket(tampered);
      assert.equal(res.valid, false);
      assert.equal(res.signature_valid, false);
      assert.ok(res.errors.includes("signature_invalid"));
    });
  }
});

describe("verifyProofPacket contract checks (error-string parity with verdict-cli)", () => {
  const basePacket = () => clone(fixture.vectors[0].packet);

  it("rejects payment above the declared max price", async () => {
    const packet = basePacket();
    packet.payment = { gateway: "cloudflare-x402", amount_usd: "2.00" };
    const res = await validateProofPacket(packet);
    assert.equal(res.valid, false);
    assert.ok(res.errors.includes("payment.amount_usd must not exceed unit.max_amount_usd"));
  });

  it("rejects a statement/statement_sha256 binding mismatch", async () => {
    const packet = basePacket();
    packet.claim.statement_sha256 = "0".repeat(64);
    const res = await validateProofPacket(packet);
    assert.equal(res.valid, false);
    assert.ok(res.errors.includes("claim.statement_sha256 does not match claim.statement"));
  });

  it("rejects a malformed statement_sha256", async () => {
    const packet = basePacket();
    packet.claim = { statement_sha256: "NOT-HEX" };
    const res = await validateProofPacket(packet);
    assert.equal(res.valid, false);
    assert.ok(res.errors.includes("claim.statement_sha256 must be 64 lowercase hex chars"));
  });

  it("legacy council receipts cannot masquerade as proof packets", async () => {
    const res = await verifyProofPacket({
      envelope: {
        protocol: "VERDICT/v1",
        receipt: {
          attestation: { algorithm: "sha256-chain", chain_hash: "a".repeat(64) },
          stage_1_responses: [],
        },
        content_hash: "b".repeat(64),
        signature: "c".repeat(128),
        signer_pubkey: "d".repeat(64),
      },
    });
    assert.equal(res.kind, "verdict_v1_envelope");
    assert.equal(res.valid, false);
    assert.ok(res.errors.includes(`schema must be ${PROOF_PACKET_SCHEMA}`));
    assert.ok(res.errors.includes("signature_invalid"));
  });

  it("wrong envelope protocol is invalid even when the signature holds", async () => {
    const env = clone(fixture.vectors[0].envelope);
    env.protocol = "VERDICT/v2";
    const res = await verifyProofPacket({ envelope: env });
    assert.equal(res.signature_valid, true);
    assert.equal(res.valid, false);
    assert.ok(res.errors.includes("envelope.protocol must be VERDICT/v1"));
  });

  it("throws on unrecognizable input", async () => {
    await assert.rejects(() => verifyProofPacket({ not: "a packet" }), /proof packet/);
  });
});
